# Generated by Django 3.1.4 on 2021-01-04 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuser',
            name='subscription_expiry_date',
            field=models.DateField(default=datetime.date(1066, 12, 3)),
        ),
    ]
